apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-example
  labels:
    name: k8s-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: k8s-example
    spec:
      containers:
        - name: k8s-example
          image: icrosby/k8s-example
          ports:
            - containerPort: 8080
